# Generated by Django 3.2.25 on 2024-06-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('games_for_sale', models.ManyToManyField(blank=True, related_name='games_for_sale', to='marketplace.Game')),
                ('games_owned', models.ManyToManyField(blank=True, related_name='games_owned', to='marketplace.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
