# Generated by Django 3.2.25 on 2024-10-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240617_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='games_for_sale',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='games_owned',
        ),
    ]
