# Generated by Django 3.2.25 on 2024-06-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('role_playing', 'Role-playing'), ('cooperatives', 'Cooperatives'), ('bluffing', 'Bluffing'), ('area_control', 'Area control'), ('placement', 'Placement'), ('memory', 'Memory'), ('miniatures', 'Miniatures'), ('war_games', 'War games'), ('worker_placement', 'Worker placement'), ('strategy', 'Strategy'), ('deck_building', 'Deck Building'), ('city_building', 'City Building'), ('party_games', 'Party Games'), ('storytelling', 'Storytelling')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_delivery_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('as_new', 'As new'), ('great', 'Great'), ('good', 'Good'), ('fair', 'Fair'), ('signs_of_time', 'Signs of time'), ('heavily_used', 'Heavily used')], max_length=15)),
                ('image', models.ImageField(upload_to='game_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField()),
                ('seller_comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='marketplace.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
