# Generated by Django 3.2.25 on 2024-05-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('as_new', 'As new'), ('great', 'Great'), ('good', 'Good'), ('fair', 'Fair'), ('signs_of_times', 'Signs of times'), ('heavily_used', 'Heavily used')], max_length=15)),
                ('image', models.ImageField(upload_to='game_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField()),
                ('seller_comment', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
