# Generated by Django 3.2.25 on 2024-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20240525_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='game',
            name='listing_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
