# Generated by Django 3.2.25 on 2024-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
