# Generated by Django 3.2.25 on 2024-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_game_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='condition',
            field=models.CharField(choices=[('as_new', 'Condition as new'), ('great', 'Great condition'), ('good', 'Good condition'), ('fair', 'Fair condition'), ('signs_of_time', 'Signs of time'), ('heavily_used', 'Heavily used')], max_length=15),
        ),
    ]
