# Generated by Django 3.2.25 on 2024-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_game_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('role_playing', 'Role-playing'), ('cooperatives', 'Cooperatives'), ('bluffing', 'Bluffing'), ('area_control', 'Area control'), ('placement', 'Placement'), ('memory', 'Memory'), ('miniatures', 'Miniatures'), ('war_games', 'War games'), ('worker_placement', 'Worker placement'), ('strategy', 'Strategy'), ('deck_building', 'Deck Building'), ('city_building', 'City Building'), ('party_games', 'Party Games'), ('storytelling', 'Storytelling')], max_length=100),
        ),
    ]
