# Generated by Django 3.2.25 on 2024-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20240601_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sku',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
